title: "Cassian 통합 운명학 분석"
description: "Cassian의 일곱 체계 운명 분석 - 명리학부터 Gene Keys까지"
author: "Cassian Research Lab"
theme: minima

# 기본 설정
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Minima 테마 설정
minima:
  skin: dark
  social_links:
    linkedin: your-linkedin
    github: your-github

# 네비게이션 메뉴
header_pages:
  - about.md
  - analysis.md
  - methodology.md
  - references.md
  - contact.md

# 언어 설정
lang: ko-KR
